import Head from "next/head";

import "bootstrap/dist/css/bootstrap.min.css"; // 引入 Bootstrap CSS
import Script from "next/script";
import { useEffect } from "react";
import style from "../styles/style.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/opendGo.png" />
      </Head>

      <header>
        <nav className="nav nav-pills flex-column flex-sm-row">
          <a
            className="flex-sm-fill text-sm-center nav-link active"
            aria-current="page"
            href="#"
          >
            工作區
          </a>
          <a
            className="flex-sm-fill text-sm-center nav-link"
            href="./history.html"
          >
            歷史紀錄
          </a>
          <a
            className="flex-sm-fill text-sm-center nav-link"
            href="./edit.html"
          >
            功能編輯
          </a>
          <a
            className="flex-sm-fill text-sm-center nav-link disabled"
            aria-disabled="true"
            href="#"
          >
            會員專區
          </a>
        </nav>
      </header>
      <main>
        <section className={style["cal-Area"]}>
          <form action="">
            <section className={style["yoichi-block yoichi-block-title"]}>
              <div className={style["yoichi-p-name"]}>商品名稱</div>
              <div className={style["yoichi-p-number"]}>數量</div>
              <div className={style["yoichi-p-btns"]}>操作</div>
            </section>
          </form>
          <section className={style["totalize"]}>
            <div className={style["yoichi-order"]}>
              <div className={`${style["yoichi-orderTime"]} yoichi-orderTime `}>
                <p>time</p>
              </div>
              <div className={style["yoichi-orderNumber"]}>
                <p>No.110</p>
              </div>
            </div>
            <div className={style["yoichi-calculating"]}>
              <div className={style["yoichi-subtotalArea"]}>
                <div className={style["yoichi-subtotal"]}>
                  <p>小記</p>
                </div>
                <div className={style["yoichi-subtotalValue"]}></div>
              </div>
              <div className={style["yoichi-discountArea"]}>
                <div className={style["yoichi-discount"]}>
                  <p>折扣</p>
                </div>
                <div className={style["yoichi-discountValue"]}></div>
              </div>
              <div className={style["yoichi-totalArea"]}>
                <div className={style["yoichi-total"]}>
                  <p>總價</p>
                </div>
                <div className={style["yoichi-totalValue"]}></div>
              </div>
            </div>
            <div className={style["yoichi-split"]}>
              <div className={style["yoichi-tiptool"]}>
                <p>模擬鎖</p>
              </div>
              <div className={style["yoichi-generate"]}>
                <button
                  className={`yoichi-order-create yoichi-order-send btn btn-secondary`}
                >
                  送出
                </button>
              </div>
            </div>
          </section>
        </section>
        <section className={style["presentation-Area"]}></section>
      </main>
      <aside className={style["floating-element"]}>
        <button
          type="button"
          className={`newOrderBtn btn btn-primary`}
          data-bs-target="#Modal-add-product"
        >
          +
        </button>
      </aside>

      <footer className={style.footer}>
        &copy; Made By
        <a
          href="mailto:qw28425382694@gmail.com"
          title="qw28425382694@gmail.com"
        >
          Oni
        </a>
      </footer>
    </div>
  );
}
